# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\learning_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from tools.data_preparation import DataPreparation
from nltk.lm.models import MLE
from tools.poem_builder import PoemBuilder
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):

    def load_model(self):
          
          my_data=DataPreparation("shak-2","shak-2")
          model=MLE(2,vocabulary=my_data.vocabulary,counter=my_data.ngram_counter)
          model.fit([my_data.sentences])
          self.poem_builder=PoemBuilder(model) 
    
    def generate_poem(self):
        self.label.setText(str(self.poem_builder.fill_poem()))

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(710, 658)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.appTitle = QtWidgets.QLabel(self.centralwidget)
        self.appTitle.setGeometry(QtCore.QRect(230, 10, 241, 111))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(49, 170, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 170, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.appTitle.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Vladimir Script")
        font.setPointSize(26)
        self.appTitle.setFont(font)
        self.appTitle.setWordWrap(False)
        self.appTitle.setObjectName("appTitle")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(500, 300, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setWhatsThis("")
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.generate_poem)
        self.poemFrame = QtWidgets.QFrame(self.centralwidget)
        self.poemFrame.setGeometry(QtCore.QRect(50, 160, 301, 301))
        self.poemFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.poemFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.poemFrame.setObjectName("poemFrame")
        self.label = QtWidgets.QLabel(self.poemFrame)
        self.label.setGeometry(QtCore.QRect(10, 10, 400, 300))
        self.label.setIndent(0)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 710, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.appTitle.setText(_translate("MainWindow", "Cooking Poetry"))
        self.pushButton.setText(_translate("MainWindow", "Build my poem !"))
        self.label.setText(_translate("MainWindow", "Ready to cook !"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.load_model()
    MainWindow.show()
    sys.exit(app.exec_())
